spring:
  datasource:
#    url: jdbc:hsqldb:hsql:/localhost:9001/integrator
#    driverClassName: org.hsqldb.jdbcDriver
#    username: root
#    password: pass
    url: jdbc:sqlserver://localhost;databaseName=iyzico
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: mssql_password1234
    hikari:
      pool-name: integrator-db-pool
  jpa:
    hibernate:
      ddl-auto: update
iyzico:
  base-url: https://sandbox-api.iyzipay.com
  api-key: sandbox-wP19ADAs7HEf8fVEQpysbT78V8kC6ZGO
  secret-key: sandbox-5Rk3intHwG3dB7ynWLKrzsTBHgNF4P0N